services:
  nosqlmongodbapi:
    container_name: nosqlmongodbapi
    image: nosqlmongodbapi
    build:
      context: .
      dockerfile: NoSQL.MongoDB.Api/Dockerfile
    ports:
        - "127.0.0.1:8082:8080"
        - "127.0.0.1:8083:8081"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        # https://www.mongodb.com/docs/manual/reference/connection-string/#connection-string-components
        # when using specific user other than admin, database name should be specified and authSource should not be used
        - MongoDB__ConnectionString=mongodb://dev:S3cr3tPFGDdcv34@mongo:27017/sample_mflix
        - MongoDB__Database=sample_mflix
    depends_on:
      - mongo
  
  # mongo
  mongo:
    container_name: mongo
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=sample_mflix
      - MONGODB_ROOT_USERNAME=root
      - MONGODB_ROOT_PASSWORD=S3cr3tPFGDssw0rd
    volumes:
      - mongo-data:/bitnami/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  
  # mongo-express
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=StrongPassword
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=S3cr3tPFGDssw0rd


volumes:
    mongo-data: {}